// protobuf3版本声明

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: tokenlist.proto

// 在proto中的包名

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 枚举类型
type Token_CoinType int32

const (
	Token_OIP10 Token_CoinType = 0
	Token_OIP20 Token_CoinType = 1
)

// Enum value maps for Token_CoinType.
var (
	Token_CoinType_name = map[int32]string{
		0: "OIP10",
		1: "OIP20",
	}
	Token_CoinType_value = map[string]int32{
		"OIP10": 0,
		"OIP20": 1,
	}
)

func (x Token_CoinType) Enum() *Token_CoinType {
	p := new(Token_CoinType)
	*p = x
	return p
}

func (x Token_CoinType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Token_CoinType) Descriptor() protoreflect.EnumDescriptor {
	return file_tokenlist_proto_enumTypes[0].Descriptor()
}

func (Token_CoinType) Type() protoreflect.EnumType {
	return &file_tokenlist_proto_enumTypes[0]
}

func (x Token_CoinType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Token_CoinType.Descriptor instead.
func (Token_CoinType) EnumDescriptor() ([]byte, []int) {
	return file_tokenlist_proto_rawDescGZIP(), []int{0, 0}
}

// 定义token结构（message）
type Token struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// string类型
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// int32类型
	Decimal int32 `protobuf:"varint,2,opt,name=decimal,proto3" json:"decimal,omitempty"`
	// 自定义类数组
	Infos []*Token_TokenInfo `protobuf:"bytes,3,rep,name=infos,proto3" json:"infos,omitempty"`
	// 引用protobuf自带的结构
	IcoTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ico_time,json=icoTime,proto3" json:"ico_time,omitempty"`
}

func (x *Token) Reset() {
	*x = Token{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenlist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_tokenlist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_tokenlist_proto_rawDescGZIP(), []int{0}
}

func (x *Token) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Token) GetDecimal() int32 {
	if x != nil {
		return x.Decimal
	}
	return 0
}

func (x *Token) GetInfos() []*Token_TokenInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

func (x *Token) GetIcoTime() *timestamppb.Timestamp {
	if x != nil {
		return x.IcoTime
	}
	return nil
}

// 定义tokenlist（Token的集合）
type TokenList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tokens []*Token `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
}

func (x *TokenList) Reset() {
	*x = TokenList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenlist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenList) ProtoMessage() {}

func (x *TokenList) ProtoReflect() protoreflect.Message {
	mi := &file_tokenlist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenList.ProtoReflect.Descriptor instead.
func (*TokenList) Descriptor() ([]byte, []int) {
	return file_tokenlist_proto_rawDescGZIP(), []int{1}
}

func (x *TokenList) GetTokens() []*Token {
	if x != nil {
		return x.Tokens
	}
	return nil
}

// 定义子结构
type Token_TokenInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalSupply int64          `protobuf:"varint,1,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`
	CoinType    Token_CoinType `protobuf:"varint,2,opt,name=coin_type,json=coinType,proto3,enum=types.Token_CoinType" json:"coin_type,omitempty"`
}

func (x *Token_TokenInfo) Reset() {
	*x = Token_TokenInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenlist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token_TokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token_TokenInfo) ProtoMessage() {}

func (x *Token_TokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tokenlist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token_TokenInfo.ProtoReflect.Descriptor instead.
func (*Token_TokenInfo) Descriptor() ([]byte, []int) {
	return file_tokenlist_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Token_TokenInfo) GetTotalSupply() int64 {
	if x != nil {
		return x.TotalSupply
	}
	return 0
}

func (x *Token_TokenInfo) GetCoinType() Token_CoinType {
	if x != nil {
		return x.CoinType
	}
	return Token_OIP10
}

var File_tokenlist_proto protoreflect.FileDescriptor

var file_tokenlist_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa4, 0x02, 0x0a, 0x05, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x64,
	0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x65,
	0x63, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x2c, 0x0a, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69, 0x6e,
	0x66, 0x6f, 0x73, 0x12, 0x35, 0x0a, 0x08, 0x69, 0x63, 0x6f, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x07, 0x69, 0x63, 0x6f, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x62, 0x0a, 0x09, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x12, 0x32, 0x0a, 0x09, 0x63, 0x6f,
	0x69, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x43, 0x6f, 0x69, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x63, 0x6f, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x20,
	0x0a, 0x08, 0x43, 0x6f, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x49,
	0x50, 0x31, 0x30, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x49, 0x50, 0x32, 0x30, 0x10, 0x01,
	0x22, 0x31, 0x0a, 0x09, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24, 0x0a,
	0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x06, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x73, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x3b, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tokenlist_proto_rawDescOnce sync.Once
	file_tokenlist_proto_rawDescData = file_tokenlist_proto_rawDesc
)

func file_tokenlist_proto_rawDescGZIP() []byte {
	file_tokenlist_proto_rawDescOnce.Do(func() {
		file_tokenlist_proto_rawDescData = protoimpl.X.CompressGZIP(file_tokenlist_proto_rawDescData)
	})
	return file_tokenlist_proto_rawDescData
}

var file_tokenlist_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tokenlist_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tokenlist_proto_goTypes = []interface{}{
	(Token_CoinType)(0),           // 0: types.Token.CoinType
	(*Token)(nil),                 // 1: types.Token
	(*TokenList)(nil),             // 2: types.TokenList
	(*Token_TokenInfo)(nil),       // 3: types.Token.TokenInfo
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_tokenlist_proto_depIdxs = []int32{
	3, // 0: types.Token.infos:type_name -> types.Token.TokenInfo
	4, // 1: types.Token.ico_time:type_name -> google.protobuf.Timestamp
	1, // 2: types.TokenList.tokens:type_name -> types.Token
	0, // 3: types.Token.TokenInfo.coin_type:type_name -> types.Token.CoinType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tokenlist_proto_init() }
func file_tokenlist_proto_init() {
	if File_tokenlist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tokenlist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Token); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokenlist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokenlist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Token_TokenInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tokenlist_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tokenlist_proto_goTypes,
		DependencyIndexes: file_tokenlist_proto_depIdxs,
		EnumInfos:         file_tokenlist_proto_enumTypes,
		MessageInfos:      file_tokenlist_proto_msgTypes,
	}.Build()
	File_tokenlist_proto = out.File
	file_tokenlist_proto_rawDesc = nil
	file_tokenlist_proto_goTypes = nil
	file_tokenlist_proto_depIdxs = nil
}
