// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: 1_getters_gogo.proto

package gogoprotobuf

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Struct struct {
	Salary               int32    `protobuf:"varint,1,opt,name=salary,proto3" json:"salary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Struct) Reset()         { *m = Struct{} }
func (m *Struct) String() string { return proto.CompactTextString(m) }
func (*Struct) ProtoMessage()    {}
func (*Struct) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d9a1fcb8d6f3ff, []int{0}
}
func (m *Struct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Struct.Unmarshal(m, b)
}
func (m *Struct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Struct.Marshal(b, m, deterministic)
}
func (m *Struct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Struct.Merge(m, src)
}
func (m *Struct) XXX_Size() int {
	return xxx_messageInfo_Struct.Size(m)
}
func (m *Struct) XXX_DiscardUnknown() {
	xxx_messageInfo_Struct.DiscardUnknown(m)
}

var xxx_messageInfo_Struct proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Struct)(nil), "types.Struct")
}

func init() { proto.RegisterFile("1_getters_gogo.proto", fileDescriptor_d2d9a1fcb8d6f3ff) }

var fileDescriptor_d2d9a1fcb8d6f3ff = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x31, 0x8c, 0x4f, 0x4f,
	0x2d, 0x29, 0x49, 0x2d, 0x2a, 0x8e, 0x4f, 0xcf, 0x4f, 0xcf, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x2d, 0xa9, 0x2c, 0x48, 0x2d, 0x96, 0xd2, 0x4d, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2,
	0x4b, 0xce, 0xcf, 0xd5, 0x07, 0xc9, 0xea, 0x83, 0x65, 0x93, 0x4a, 0xd3, 0xc0, 0x3c, 0x30, 0x47,
	0x1f, 0xa1, 0x4b, 0x49, 0x8d, 0x8b, 0x2d, 0xb8, 0xa4, 0xa8, 0x34, 0xb9, 0x44, 0x48, 0x8c, 0x8b,
	0xad, 0x38, 0x31, 0x27, 0xb1, 0xa8, 0x52, 0x82, 0x51, 0x81, 0x51, 0x83, 0x35, 0x08, 0xca, 0xb3,
	0x62, 0xe9, 0x58, 0x20, 0xcf, 0xe0, 0x24, 0x18, 0xc5, 0xaf, 0xa7, 0x6f, 0x0d, 0x37, 0x22, 0xa9,
	0x34, 0x2d, 0x89, 0x0d, 0xcc, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x8e, 0xee, 0x6e,
	0x8f, 0x00, 0x00, 0x00,
}
