// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: 8_customtype_gogo.proto

package gogoprotobuf

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_test_custom "github.com/gogo/protobuf/test/custom"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Test8 struct {
	Code                 []github_com_gogo_protobuf_test_custom.Uint128 `protobuf:"bytes,1,rep,name=code,proto3,customtype=github.com/gogo/protobuf/test/custom.Uint128" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                       `json:"-"`
	XXX_unrecognized     []byte                                         `json:"-"`
	XXX_sizecache        int32                                          `json:"-"`
}

func (m *Test8) Reset()         { *m = Test8{} }
func (m *Test8) String() string { return proto.CompactTextString(m) }
func (*Test8) ProtoMessage()    {}
func (*Test8) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd5942d65bdc885, []int{0}
}
func (m *Test8) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test8.Unmarshal(m, b)
}
func (m *Test8) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test8.Marshal(b, m, deterministic)
}
func (m *Test8) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test8.Merge(m, src)
}
func (m *Test8) XXX_Size() int {
	return xxx_messageInfo_Test8.Size(m)
}
func (m *Test8) XXX_DiscardUnknown() {
	xxx_messageInfo_Test8.DiscardUnknown(m)
}

var xxx_messageInfo_Test8 proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Test8)(nil), "types.Test8")
}

func init() { proto.RegisterFile("8_customtype_gogo.proto", fileDescriptor_1fd5942d65bdc885) }

var fileDescriptor_1fd5942d65bdc885 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xb7, 0x88, 0x4f, 0x2e,
	0x2d, 0x2e, 0xc9, 0xcf, 0x2d, 0xa9, 0x2c, 0x48, 0x8d, 0x4f, 0xcf, 0x4f, 0xcf, 0xd7, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x09, 0x14, 0x4b, 0xe9, 0xa6, 0x67, 0x96, 0x64, 0x94, 0x26,
	0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x83, 0x64, 0xf5, 0xc1, 0xb2, 0x49, 0xa5, 0x69, 0x60, 0x1e, 0x98,
	0xa3, 0x8f, 0xd0, 0xa5, 0xe4, 0xcb, 0xc5, 0x1a, 0x92, 0x5a, 0x5c, 0x62, 0x21, 0xe4, 0xc2, 0xc5,
	0x92, 0x9c, 0x9f, 0x92, 0x2a, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0xe3, 0x64, 0x70, 0xeb, 0x9e, 0xbc,
	0x0e, 0x4e, 0x93, 0x4a, 0x52, 0x8b, 0x4b, 0xf4, 0x21, 0xae, 0xd0, 0x0b, 0xcd, 0xcc, 0x2b, 0x31,
	0x34, 0xb2, 0x08, 0x02, 0xeb, 0x76, 0x12, 0x8c, 0xe2, 0xd7, 0xd3, 0xb7, 0x86, 0xdb, 0x94, 0x54,
	0x9a, 0x96, 0xc4, 0x06, 0x66, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x50, 0x49, 0x6f, 0xb6,
	0xb9, 0x00, 0x00, 0x00,
}
